### PR TITLE
Fix/error instead of warn

### PR DESCRIPTION
**Pull request by jkoenig134**

### CODE REVIEW

**Comment by jkoenig134** [comment]
@tnotheis any idea why we marked this as warning??

**Review by sebbi08 — APPROVED** [review]

**Comment by tnotheis** [comment]
@jkoenig134 There may be places where we don't want to cover every possible case.

**Comment by sebbi08** [comment]
> @jkoenig134 There may be places where we don't want to cover every possible case.

Ok, but shouldn't those cases have a default statement? This would satisfy this rule.

**Comment by jkoenig134** [comment]
Shouldn't this be made explicitly using a default satement?

**Comment by jkoenig134** [comment]
:D what sebbi says :D

**Comment by jkoenig134** [comment]
@tnotheis additionally we don't have any warnings currently so it should be fine to merge this.

**Pull request merged**
